version: '2'

services:
  free5gc-upf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upf1
    command: | 
        /bin/bash -c "
        iptables -t nat -I POSTROUTING -s 60.60.0.0/24 -o servicenet -j MASQUERADE
        /dynamicpath/bin/monitor -h 10.200.200.101:8888 -eth0 rx=200,tx=200 &
        /gofree5gc/src/upf/build/bin/free5gc-upfd -f /config/upfcfg.yaml
        "
    privileged: true
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
      - "./dynamicpath:/dynamicpath"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    expose:
      - "2152"
      - "8805"
      - "8888"
    networks:
      privnet:
        ipv4_address: 10.200.200.101
      servicenet:
        ipv4_address: 60.60.1.101

  db:
    image: mongo
    container_name: mongodb
    command: mongod --port 27017
    expose:
      - "27017"
    networks:
      privnet:
        ipv4_address: 10.200.200.1

  free5gc-nrf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nrf
    command: |
      /bin/bash -c "
      ./bin/nrf
      "
    expose:
      - "29510"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    environment:
      DB_URI: mongodb://db/free5gc
    networks:
      privnet:
        ipv4_address: 10.200.200.2
    depends_on:
      - db

  free5gc-amf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amf
    command: |
      /bin/bash -c "
      ./bin/amf
      "
    expose:
      - "29518"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.3
    depends_on:
      - free5gc-nrf

  free5gc-ausf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ausf
    command: |
      /bin/bash -c "
      ./bin/ausf
      "
    expose:
      - "29509"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.4
    depends_on:
      - free5gc-nrf

  free5gc-nssf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nssf
    command: |
      /bin/bash -c "
      ./bin/nssf
      "
    expose:
      - "29531"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.5
    depends_on:
      - free5gc-nrf

  free5gc-pcf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pcf
    command: |
      /bin/bash -c "
      ./bin/pcf
      "
    expose:
      - "29507"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.6
    depends_on:
      - free5gc-nrf

  free5gc-smf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smf
    command: |
      /bin/bash -c "
      ./bin/smf -smfcfg /config/smfcfg.conf
      "
    expose:
      - "38413"
      - "29502"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.7
    depends_on:
      - free5gc-nrf
      - free5gc-upf

  free5gc-udm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udm
    command: |
      /bin/bash -c "
      ./bin/udm
      "
    expose:
      - "29503"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.8
    depends_on:
      - free5gc-nrf

  free5gc-udr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udr
    command: |
      /bin/bash -c "
      ./bin/udr
      "
    expose:
      - "29504"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    environment:
      DB_URI: mongodb://db/free5gc
    networks:
      privnet:
        ipv4_address: 10.200.200.9
    depends_on:
      - db
    depends_on:
      - free5gc-nrf
  radio-simulator:
    build:
      context: .
      dockerfile: Dockerfile_Radio
    container_name: simulator
    command: | 
        /bin/bash -c "
        sleep 0.5
        /radio_simulator/run_in_docker.sh 60.60.1.0/24
        "
    privileged: true
    volumes:
      - "./config_radio:/radio_simulator/config"
      - "./radio_simulator:/radio_simulator"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      privnet:
        ipv4_address: 10.200.200.100
    depends_on:
      - free5gc-amf

        #service-iperf3:
        #build:
        #context: .
        #dockerfile: Dockerfile_service
        #container_name: iperf3
        #expose:
        #- "5201"
        #networks:
        #servicenet:
        #ipv4_address: 60.60.1.1
        #tty: true

networks:
  privnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.200.0/24
          gateway: 10.200.200.254
  servicenet:
    driver: bridge
    ipam:
      config:
        - subnet: 60.60.1.0/24
          gateway: 60.60.1.254
