version: '2'

services:
  free5gc-upf1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upf1
    command: | 
        /bin/bash -c "
        sysctl fs.mqueue.msg_default=5
        # cd /gofree5gc/src/upf && rm -rf ./build && mkdir -p build && cd build && cmake .. && make -j8
        /gofree5gc/src/upf/build/bin/free5gc-upfd -f /config/upf1cfg.yaml &
        sleep 0.05
        ip link set dev upfgtp0 mtu 65535
        /dynamicpath/bin/monitor -h upf1:8888 -eth1 rx=170,tx=170 
        "
    privileged: true
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
      - "./dynamicpath:/dynamicpath"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    expose:
      - "2152"
      - "8805"
      - "8888"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.101
      2_upnet:
        ipv4_address: 10.200.201.101

  free5gc-upf2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upf2
    command: | 
        /bin/bash -c "
        sysctl fs.mqueue.msg_default=5
        # cd /gofree5gc/src/upf && rm -rf ./build && mkdir -p build && cd build && cmake .. && make -j8
        /gofree5gc/src/upf/build/bin/free5gc-upfd -f /config/upf2cfg.yaml &
        sleep 0.05
        ip link set dev upfgtp0 mtu 65535
        /dynamicpath/bin/monitor -h upf2:8888 -eth1 rx=570,tx=570 
        "
    privileged: true
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
      - "./dynamicpath:/dynamicpath"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    expose:
      - "2152"
      - "8805"
      - "8888"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.102
      2_upnet:
        ipv4_address: 10.200.201.102

  free5gc-upf3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upf3
    command: | 
        /bin/bash -c "
        sysctl fs.mqueue.msg_default=5
        # cd /gofree5gc/src/upf && rm -rf ./build && mkdir -p build && cd build && cmake .. && make -j8
        /gofree5gc/src/upf/build/bin/free5gc-upfd -f /config/upf3cfg.yaml &
        sleep 0.05
        ip link set dev upfgtp0 mtu 65535
        /dynamicpath/bin/monitor -h upf3:8888 -eth1 rx=370,tx=370 
        "
    privileged: true
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
      - "./dynamicpath:/dynamicpath"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    expose:
      - "2152"
      - "8805"
      - "8888"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.103
      2_upnet:
        ipv4_address: 10.200.201.103

  free5gc-upf4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upf4
    command: | 
        /bin/bash -c "
        sysctl fs.mqueue.msg_default=5
        # cd /gofree5gc/src/upf && rm -rf ./build && mkdir -p build && cd build && cmake .. && make -j8
        /gofree5gc/src/upf/build/bin/free5gc-upfd -f /config/upf4cfg.yaml &
        sleep 0.05
        ip link set dev upfgtp0 mtu 65535
        /dynamicpath/bin/monitor -h upf4:8888 -eth1 rx=570,tx=570 
        "
    privileged: true
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
      - "./dynamicpath:/dynamicpath"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    expose:
      - "2152"
      - "8805"
      - "8888"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.104
      2_upnet:
        ipv4_address: 10.200.201.104

  free5gc-upf5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upf5
    command: | 
        /bin/bash -c "
        sysctl fs.mqueue.msg_default=5
        # cd /gofree5gc/src/upf && rm -rf ./build && mkdir -p build && cd build && cmake .. && make -j8
        /gofree5gc/src/upf/build/bin/free5gc-upfd -f /config/upf5cfg.yaml &
        sleep 0.05
        ip link set dev upfgtp0 mtu 65535
        /dynamicpath/bin/monitor -h upf5:8888 -eth1 rx=370,tx=370 
        "
    privileged: true
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
      - "./dynamicpath:/dynamicpath"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    expose:
      - "2152"
      - "8805"
      - "8888"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.105
      2_upnet:
        ipv4_address: 10.200.201.105

  free5gc-upf6:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upf6
    command: | 
        /bin/bash -c "
        sysctl fs.mqueue.msg_default=5
        # cd /gofree5gc/src/upf && rm -rf ./build && mkdir -p build && cd build && cmake .. && make -j8
        /gofree5gc/src/upf/build/bin/free5gc-upfd -f /config/upf6cfg.yaml &
        sleep 0.05
        ip link set dev upfgtp0 mtu 65535
        /dynamicpath/bin/monitor -h upf6:8888 -eth1 rx=470,tx=470 
        "
    privileged: true
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
      - "./dynamicpath:/dynamicpath"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    expose:
      - "2152"
      - "8805"
      - "8888"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.106
      2_upnet:
        ipv4_address: 10.200.201.106

  free5gc-upf7:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upf7
    command: | 
        /bin/bash -c "
        sysctl fs.mqueue.msg_default=5
        # cd /gofree5gc/src/upf && rm -rf ./build && mkdir -p build && cd build && cmake .. && make -j8
        /gofree5gc/src/upf/build/bin/free5gc-upfd -f /config/upf7cfg.yaml &
        sleep 0.05
        ip link set dev upfgtp0 mtu 65535
        /dynamicpath/bin/monitor -h upf7:8888 -eth1 rx=270,tx=270 
        "
    privileged: true
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
      - "./dynamicpath:/dynamicpath"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    expose:
      - "2152"
      - "8805"
      - "8888"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.107
      2_upnet:
        ipv4_address: 10.200.201.107

  free5gc-upf8:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upf8
    command: | 
        /bin/bash -c "
        ip route change default via 60.60.1.254 dev eth2
        iptables -t nat -I POSTROUTING -o eth2 -j MASQUERADE
        sysctl fs.mqueue.msg_default=5
        # cd /gofree5gc/src/upf && rm -rf ./build && mkdir -p build && cd build && cmake .. && make -j8
        /gofree5gc/src/upf/build/bin/free5gc-upfd -f /config/upf8cfg.yaml &
        sleep 0.05
        ip link set dev upfgtp0 mtu 65535
        /dynamicpath/bin/monitor -h upf8:8888 -eth1 rx=470,tx=470 -eth2 rx=500,tx=500 
        "
    privileged: true
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
      - "./dynamicpath:/dynamicpath"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    expose:
      - "2152"
      - "8805"
      - "8888"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.108
      2_upnet:
        ipv4_address: 10.200.201.108
      3_servicenet:
        ipv4_address: 60.60.1.108

  free5gc-upf9:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upf9
    command: | 
        /bin/bash -c "
        ip route change default via 60.60.1.254 dev eth2
        iptables -t nat -I POSTROUTING -o eth2 -j MASQUERADE
        sysctl fs.mqueue.msg_default=5
        # cd /gofree5gc/src/upf && rm -rf ./build && mkdir -p build && cd build && cmake .. && make -j8
        /gofree5gc/src/upf/build/bin/free5gc-upfd -f /config/upf9cfg.yaml &
        sleep 0.05
        ip link set dev upfgtp0 mtu 65535
        /dynamicpath/bin/monitor -h upf9:8888 -eth1 rx=370,tx=370 -eth2 rx=400,tx=400 
        "
    privileged: true
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
      - "./dynamicpath:/dynamicpath"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    expose:
      - "2152"
      - "8805"
      - "8888"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.109
      2_upnet:
        ipv4_address: 10.200.201.109
      3_servicenet:
        ipv4_address: 60.60.1.109

  free5gc-upf10:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upf10
    command: | 
        /bin/bash -c "
        ip route change default via 60.60.1.254 dev eth2
        iptables -t nat -I POSTROUTING -o eth2 -j MASQUERADE
        sysctl fs.mqueue.msg_default=5
        # cd /gofree5gc/src/upf && rm -rf ./build && mkdir -p build && cd build && cmake .. && make -j8
        /gofree5gc/src/upf/build/bin/free5gc-upfd -f /config/upf10cfg.yaml &
        sleep 0.05
        ip link set dev upfgtp0 mtu 65535
        /dynamicpath/bin/monitor -h upf10:8888 -eth1 rx=70,tx=70 -eth2 rx=100,tx=100 
        "
    privileged: true
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
      - "./dynamicpath:/dynamicpath"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    expose:
      - "2152"
      - "8805"
      - "8888"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.110
      2_upnet:
        ipv4_address: 10.200.201.110
      3_servicenet:
        ipv4_address: 60.60.1.110

  free5gc-upf11:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upf11
    command: | 
        /bin/bash -c "
        sysctl fs.mqueue.msg_default=5
        # cd /gofree5gc/src/upf && rm -rf ./build && mkdir -p build && cd build && cmake .. && make -j8
        /gofree5gc/src/upf/build/bin/free5gc-upfd -f /config/upf11cfg.yaml &
        sleep 0.05
        ip link set dev upfgtp0 mtu 65535
        /dynamicpath/bin/monitor -h upf11:8888 -eth1 rx=10000,tx=10000 
        "
    privileged: true
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
      - "./dynamicpath:/dynamicpath"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - "/dev/net/tun:/dev/net/tun"
    expose:
      - "2152"
      - "8805"
      - "8888"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.111
      2_upnet:
        ipv4_address: 10.200.201.111

  db:
    image: mongo
    container_name: mongodb
    command: mongod --port 27017
    expose:
      - "27017"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.1

  free5gc-nrf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nrf
    command: |
      /bin/bash -c "
      ./bin/nrf
      "
    expose:
      - "29510"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    environment:
      DB_URI: mongodb://db/free5gc
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.2
    depends_on:
      - db

  free5gc-amf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amf
    command: |
      /bin/bash -c "
      ./bin/amf
      "
    expose:
      - "29518"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.3
    depends_on:
      - free5gc-nrf

  free5gc-ausf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ausf
    command: |
      /bin/bash -c "
      ./bin/ausf
      "
    expose:
      - "29509"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.4
    depends_on:
      - free5gc-nrf

  free5gc-nssf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nssf
    command: |
      /bin/bash -c "
      ./bin/nssf
      "
    expose:
      - "29531"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.5
    depends_on:
      - free5gc-nrf

  free5gc-pcf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pcf
    command: |
      /bin/bash -c "
      ./bin/pcf
      "
    expose:
      - "29507"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.6
    depends_on:
      - free5gc-nrf
      - free5gc-amf

  free5gc-smf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smf
    command: |
      /bin/bash -c "
      sleep 0.5
      ./bin/smf -smfcfg /config/smfcfg.test.conf
      "
    expose:
      - "38413"
      - "29502"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.7
    depends_on:
      - free5gc-nrf
      - load-balancer

  free5gc-udm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udm
    command: |
      /bin/bash -c "
      ./bin/udm
      "
    expose:
      - "29503"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.8
    depends_on:
      - free5gc-nrf

  free5gc-udr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udr
    command: |
      /bin/bash -c "
      ./bin/udr
      "
    expose:
      - "29504"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/gofree5gc/config"
    environment:
      DB_URI: mongodb://db/free5gc
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.9
    depends_on:
      - db
    depends_on:
      - free5gc-nrf

  load-balancer:
    build:
      context: .
      dockerfile: Dockerfile_Balancer
    container_name: balancer
    command: | 
        /bin/bash -c "
        sleep 0.3
        /dynamicpath/bin/balancer -lbcfg /config/lbcfg_test1.conf
        "
    volumes:
      - "./config_balancer:/config"
      - "./dynamicpath:/dynamicpath"
    expose:
      - "9487"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.10
    depends_on:
      - free5gc-upf1
      - free5gc-upf2
      - free5gc-upf3
      - free5gc-upf4
      - free5gc-upf5
      - free5gc-upf6
      - free5gc-upf7
      - free5gc-upf8
      - free5gc-upf9
      - free5gc-upf10
      - radio-simulator

  radio-simulator:
    build:
      context: .
      dockerfile: Dockerfile_Radio
    container_name: simulator
    command: | 
       /bin/bash -c "
       # cd /radio_simulator/lib/libgtp5gnl && autoreconf -iv && ./configure --prefix=`pwd` && make -j`nproc`
       cd /radio_simulator && ./run.sh 60.60.2.0/24
       "
    privileged: true
    volumes:
      - "./radio_simulator:/radio_simulator"
      - "./config_radio:/radio_simulator/config"
      - "./ping_log:/ping_log"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    expose:
      - "8088"
      - "2152"
      - "9999"
    networks:
      1_cpnet:
        ipv4_address: 10.200.200.100
      2_upnet:
        ipv4_address: 10.200.201.100
    depends_on:
      - free5gc-amf
    # tty: true
        #service-iperf3:
        #build:
        #context: .
        #dockerfile: Dockerfile_service
        #container_name: iperf3
        #expose:
        #- "5201"
        #networks:
        #3_servicenet:
        #ipv4_address: 60.60.1.1
        #tty: true

networks:
  1_cpnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.200.0/24
          gateway: 10.200.200.254
  2_upnet:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 65535
    ipam:
      config:
        - subnet: 10.200.201.0/24
          gateway: 10.200.201.254
  3_servicenet:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 65535
    ipam:
      config:
        - subnet: 60.60.1.0/24
          gateway: 60.60.1.254
