From golang:latest
ENV GO111MODULE=on
ENV GOPATH="/:${GOPATH}"
WORKDIR /radio_simulator

MAINTAINER Weiting Hu <zxc6752@gmail.com>

RUN apt-get update
RUN apt-get -y install gcc cmake autoconf libtool pkg-config libmnl-dev libyaml-dev netcat tcpdump iperf

RUN go get -u -v "github.com/sirupsen/logrus"

RUN apt-get clean

